config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users

  authenticated :user do
    root 'users#show', as: :authenticated_root
  end

  root "home#index"
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_fail'
  get '/sign_out', to: 'sessions#destroy', as: :sign_out
  resources :votes, only: [:create]
  resources :users, only: [:show]
  resources :polls
  resources :groups

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, through: :memberships
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user
  has_many :vote_options, dependent: :destroy
  validates :topic, presence: true
  accepts_nested_attributes_for :vote_options, :reject_if => :all_blank, :allow_destroy => true
  def normalized_votes_for(option)
    votes_summary == 0 ? 0 : (option.votes.count.to_f / votes_summary) * 100
  end
  def votes_summary
    vote_options.inject(0) {|summary, option| summary + option.votes.count}
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :polls
  has_many :votes, dependent: :destroy
  has_many :vote_options, through: :votes
  class << self
    def from_omniauth(auth)
      uid = auth.uid
      info = auth.info.symbolize_keys!
      user = User.find_or_initialize_by(uid: uid)
      user.name = info.name
      user.image_url = info.image
      user.save!
      user
    end
  end
  def voted_for?(poll)
    vote_options.any? {|v| v.poll == poll }
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :vote_option
  counter_culture :vote_option
end

app/models/vote_option.rb
class VoteOption < ApplicationRecord
  belongs_to :poll
  validates :title, presence: true
  has_many :votes, dependent: :destroy
  has_many :users, through: :votes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # def current_user
  #   @current_user ||= User.find_by(id: cookies[:user_id]) if cookies[:user_id]
  # end
  #
  # helper_method :current_user
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:success] = 'Group was created!'
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find_by_id(params[:id])
  end

  def show
    @group = Group.find_by_id(params[:id])
  end

  def update
    @group = Group.find_by_id(params[:id])
    if @group.update_attributes(group_params)
      flash[:success] = 'Group was updated!'
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find_by_id(params[:id])
    if @group.destroy
      flash[:success] = 'Group was destroyed!'
    else
      flash[:warning] = 'Error destroying group...'
    end
    redirect_to groups_path
  end

  private

  def poll_params
    params.require(:group).permit(:title)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:success] = 'Group was created!'
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find_by_id(params[:id])
  end

  def show
    @group = Group.find_by_id(params[:id])
  end

  def update
    @group = Group.find_by_id(params[:id])
    if @group.update_attributes(group_params)
      flash[:success] = 'Group was updated!'
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find_by_id(params[:id])
    if @group.destroy
      flash[:success] = 'Group was destroyed!'
    else
      flash[:warning] = 'Error destroying group...'
    end
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @polls = Poll.all
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = current_user.polls.build(poll_params)
    if @poll.save
      flash[:success] = 'Poll was created!'
      redirect_to polls_path
    else
      render 'new'
    end
  end

  def edit
    @poll = Poll.find_by_id(params[:id])
  end

  def show
    poll = Poll.includes(:vote_options).find_by_id(params[:id])
  end

  def update
    @poll = Poll.find_by_id(params[:id])
    if @poll.update_attributes(poll_params)
      flash[:success] = 'Poll was updated!'
      redirect_to polls_path
    else
      render 'edit'
    end
  end

  def destroy
    @poll = Poll.find_by_id(params[:id])
    if @poll.destroy
      flash[:success] = 'Poll was destroyed!'
    else
      flash[:warning] = 'Error destroying poll...'
    end
    redirect_to polls_path
  end

  private

  def poll_params
    params.require(:poll).permit(:topic, vote_options_attributes: [:id, :title, :_destroy])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env['omniauth.auth'])
    cookies[:user_id] = user.id
    flash[:success] = "Welcome, #{user.name}!"
    redirect_to root_url
  end

  def destroy
    cookies.delete(:user_id)
    flash[:success] = "Goodbye!"
    redirect_to root_url
  end

  def auth_fail
    render text: "You've tried to authenticate via #{params[:strategy]}, but the following error
occurred: #{params[:message]}", status: 500
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @polls = current_user.polls
  end
  #
  # def show
  #   @user = User.includes(:vote_options).find_by_id(params[:id])
  # end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    if current_user && params[:poll] && params[:poll][:id] && params[:vote_option] && params[:vote_option][:id]
      @poll = Poll.find_by_id(params[:poll][:id])
      @option = @poll.vote_options.find_by_id(params[:vote_option][:id])
      if @option && @poll && !current_user.voted_for?(@poll)
        @option.votes.create({user_id: current_user.id})
      else
        render js: 'alert(\'Your vote cannot be saved. Have you already voted?\');'
      end
    else
      render js: 'alert(\'Your vote cannot be saved.\');'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/polls_helper.rb
# TODO: change to Bootstrap 4 markup
module PollsHelper
  def visualize_votes_for(option)
    content_tag :progress, value: "#{option.poll.normalized_votes_for(option)}", max: "100" do
      content_tag :div, class: 'progress' do
        content_tag :div, class: 'progress-bar',
                    style: "width: #{option.poll.normalized_votes_for(option)}%" do
          "#{option.votes.count}"
        end
      end
    end
  end
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <%= render 'shared/errors', object: @group %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_area :name, rows: 1, required: true, class: 'form-control' %>
  </div>
  <p class="text-center">
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/groups/index.html.erb
<% content_for(:page_header) {"Our groups"} %>
<% @groups.each do |group| %>
  <div class="well">
    <h2><%= group.name %></h2>
    <button class="btn btn-primary">Join</button>
    <button class="btn btn-default">Info</button>
  </div>
<% end %>

app/views/groups/new.html.erb
<% content_for(:page_header) {"Create a new group"} %>

<%= render 'form' %>

app/views/home/index.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
    <div class="masthead clearfix">
      <div class="inner">
        <h3 class="masthead-brand">Make Some Polls</h3>
        <nav class="nav nav-masthead">
          <a class="btn btn-primary" href="/users/sign_in">Log In</a>
          <a class="btn btn-success" href="/users/sign_up">Sign Up</a>
        </nav>
      </div>
    </div>
    <div class="inner cover">
      <h1 class="cover-heading">Make polls the easy way</h1>
      <p class="lead">Create your own polls, install them on your website, and vote on polls others have written.</p>
      <p class="lead">
        <a href="/users/sign_up" class="btn btn-lg btn-success">Sign Up - For Free</a>
      </p>
      <p>
        Already have an account? <a style="color: #0275d8;" href="/users/sign_in">Log in</a>
      </p>
    </div>
    <div class="mastfoot">
      <div class="inner">
        <p>A web app by <a href="http://www.mrscottmcallister.com" target="_blank">Scott McAllister</a>.</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Make Some Polls</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    'application', params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="site-wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/polls/_form.html.erb
<%= form_for @poll, class: "form-horizontal" do |f| %>
  <div class="container">
    <%= render 'shared/errors', object: @poll %>
    <input type="hidden" name="user_id" value="<%= current_user.id %>">

    <div class="form-group">
      <%= f.text_area :topic, rows: 1, required: true, class: 'form-control', placeholder: "Poll topic" %>
    </div>

    <div class="panel panel-default">
      <div class="panel-body">
        <%= f.fields_for :vote_options do |options_form| %>
          <%= render 'vote_option_fields', f: options_form %>
        <% end %>

        <div class="links">
          <%= link_to_add_association f, :vote_options, class: "btn btn-info" do%>
            Add Option +
          <% end %>
        </div>
      </div>
    </div>

    <p class="text-xs-center" style="padding-top:40px;">
      <%= f.submit 'Create Poll', class: 'btn btn-primary' %>
    </p>
  </div>
<% end %>

app/views/polls/_vote_option.html.erb
<div class="form-group">
  <%= content_tag :label, class: "pull-xs-left" do %>
    <% unless current_user.voted_for?(@poll) %>
      <%= radio_button_tag 'vote_option[id]', option.id %>
    <% end %>
    <%= option.title %>
  <% end %>
  <%= visualize_votes_for option %>
</div>

app/views/polls/_vote_option_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.text_field :title, class: "form-control", style: "width: 66.66%; display:inline;", required: true, placeholder: "Option Title" %>
    <%= link_to_remove_association f, class: "btn btn-danger pull-right" do%>
      Remove -
    <% end %>
  </div>
</div>

app/views/polls/_voting_form.html.erb
<%= form_tag votes_path, method: :post, remote: true, id: 'voting_form' do %>
  <%= hidden_field_tag 'poll[id]', poll.id %>

  <%= render partial: 'polls/vote_option', collection: poll.vote_options, as: :option %>

  <p><b>Total votes: <%= poll.votes_summary %></b></p>

  <% if current_user.voted_for?(poll) %>
    <p>You have already voted!</p>
  <% else %>
    <%= submit_tag 'Vote', class: 'btn btn-lg btn-primary' %>
  <% end %>
<% end %>

app/views/polls/edit.html.erb
<% content_for(:page_header) {"Edit poll"} %>
<%= render 'form' %>

app/views/polls/index.html.erb
<div class="container">
  <h2>Participate In Our Polls</h2>
  <% @polls.each do |poll| %>
    <div class="well">
      <h4><%= poll.topic %> <small>(voted: <%= poll.votes_summary %>)</small></h4>
      <!-- TODO: show voting results -->
      <%= render 'voting_form', poll: poll %>
    </div>
  <% end %>
</div>

app/views/polls/new.html.erb
<div class="container">
  <h2>Create New Poll</h2>
  <%= render 'form' %>
</div>

app/views/polls/show.html.erb
<% content_for(:page_header) {"Share your opinion"} %>
<div class="container">
<h2><%= @poll.topic %></h2>

<%= render 'voting_form' %>

</div>

<script data-turbolinks-track="true">
  $(document).ready(function() {
    var voting_form = $('#voting_form');
    voting_form.validate({
      focusInvalid: false,
      errorClass: 'alert alert-warning',
      errorElement: "div",
      errorPlacement: function(error, element) { voting_form.before(error); },
      rules: {
        'vote_option[id]': {
          required: true
        }
      },
      messages: {
        'vote_option[id]': {
          required: "Please select one of the options."
        }
      }
    });
  });
</script>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning">
    <h4>The following errors were found:</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
    <div class="container">
      <div class="clearfix">
        <button class="navbar-toggler pull-xs-right hidden-sm-up" type="button" data-toggle="collapse" data-target="#bd-main-nav" aria-controls="bd-main-nav" aria-expanded="false" aria-label="Toggle navigation">
          ☰
        </button>
      </div>
      <a class="navbar-brand" href="/" style="inline-block"><img src="/assets/icon-sm.png" style="height:25px;width:25px;"/></a>
      <div class="collapse navbar-toggleable-xs pull-right" id="bd-main-nav">
        <ul class="nav navbar-nav">
          <!--<li class="nav-item">
            <%= link_to new_group_path, class: "nav-link" do%>
              <i class="fa fa-users"></i> Groups
            <% end %>
          </li>-->
          <li class="nav-item">
            <%= link_to new_poll_path, class: "nav-link" do %>
              <i class="fa fa-plus-square"></i> Create Poll
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to '/polls', class: "nav-link" do %>
              <i class="fa fa-bar-chart"></i> View Polls
            <% end %>
          </li>
          <% if current_user %>
            <li class="nav-item">
              <%= link_to '/users/edit', class: "nav-link" do%>
                <i class="fa fa-user"></i> Profile
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do%>
                <i class="fa fa-sign-out"></i> Sign out
              <% end %>
            </li>
          <% else %>
            <li class="nav-item"><%= link_to 'Sign in', '/users/sign_in', class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h2 class="text-xs-center">Polls You've Voted On</h2>
      <% @user.vote_options.each do |option| %>
        <div class="panel panel-default">
          <div class="panel-heading">Poll title: <%= link_to option.poll.topic, poll_path(option.poll) %></div>
          <div class="panel-body">
            Your vote: <%= option.title %>
          </div>
        </div>
      <% end %>
      <% if @user.vote_options.count == 0 %>
        <p>You haven't voted yet!</p>
      <% end %>
    </div>
    <div class="col-sm-6">
      <h2 class="text-xs-center">Your Polls</h2>
      <% @polls.each do |poll| %>
        <p><%= poll.topic %> <small>(voted: <%= poll.votes_summary %>)</small></p>
      <% end %>
    </div>
  </div>
</div>

app/views/votes/create.js.erb
$('#voting_form').replaceWith('<%= j render 'polls/voting_form' %>');